#define	CONST 1
#define	ID  2
#define	INT  3
#define	EQUAL 4
#define	SEMICOLON 5
#define	COMMA 6
#define	EQUALITY 7
#define	RETURN 8
#define	OPEN_R_PARANTHESIS 9
#define	CLOSED_R_PARANTHESIS 10
#define	IF 11
#define	WHILE 12
#define	ELSE 13
#define	OPEN_B_PARANTHESIS 14
#define	COUT 15
#define	CIN 16
#define	LESSTHAN 17
#define	DIFFERENT 18
#define	MAIN 19
#define	ADDRESS 20
#define	INCLUDE 21
#define	IOSTREAM_DLL 22
#define	PLUS 23
#define	MINUS 24
#define	CLOSE_B_PARANTHESIS 25
#define	TYPEDEF 26
#define	STRUCT 27
#define FLOAT 28
#define	DOT 29
#define	MULTIPLY 30
#define USING 31
#define EMPTY 32
#define NAMESPACE 33
#define STD 34
